### ISSUE TITLE
Can not label the graph with 4

### ISSUE THREAD

**Issue by 19373254** [davidireland3/LeNSE#3]
hello, I have some poblem in creating the dataset. In paper, the graph are label 4 if the ratio is less than 0.6. But when I am labelling the graph, the solution don not including the seeds got by function imm() can get a ratio of 0.75. So I think the optimal seeds got by imm() is not  optimal.

**Comment by davidireland-iso** [comment]
If you run imm on the entire graph, then you will get the global solutions. The idea in creating the dataset is to sample some subgraphs, run imm _on the subgraph_, which will obtain a potentially sub-optimal solution, and compare the score of these seeds _evaluated on the entire graph_ to the score of the global solution. This is explained in the paper.

**Comment by davidireland-iso** [comment]
Based on your comments, you might be experiencing the problem that for your subgraph size (i.e. it is too big) that the minimum score IMM gets relative to the main graph cannot be less than 0.6. Whilst 0.6 worked for most larger graphs, sometimes it would need to be lowered for some of the smaller graphs. For instance, the smallest graphs we used I only used 3 classes because even using 0 optimal seeds in the subgraph, IMM would still find a solution with ratio > 0.6. So I would recommend first trying to tune 0.6 to some lower value, or using a smaller number of classes.
